version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./docker/tkch.sh:/docker-entrypoint-initdb.d/tkch.sh"
    ports:
      - "5432:5432"